services:
  app:
    build: .
    image: my-spring-app
    container_name: spring-container
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}