spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

jwt:
  header: Authorization
  secret: 2b7e151628aed2a6abf7158809cf4f3c762e7160d6d9d3b6fb6d88e8e846c61e
